name: Build Gleecexample

on: push

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true

      - name: Download dependencies
        run: |
          go mod download
          go install github.com/gopher-fleece/gleece

      - name: Build
        run: |
          # Generate the specification & routes
          gleece
          # Build the server
          go build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gleecexample
          path: |
            gleecexample
            openapi/swagger.json
          retention-days: 7